name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your desired branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x  # Choose the desired Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v1.2.3
      env:
        API_KEY: ${{ secrets.API_KEY }} # Load the API key from GitHub Secrets
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        ENV_FILE: API_KEY=${{ secrets.API_KEY }} # Set the API_KEY environment variable