name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # Trigger deployment on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        uses: actions/deploy-github-pages@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # Deploy to the gh-pages branch
          folder: build  # Replace with your build output folder (if applicable)
          push: true

